services:
  db:
    image: mysql:8.0
    container_name: m295-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: m295
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    restart: unless-stopped

volumes:
  db_data:

